server:
  port: 9099

spring:
  datasource:
    url: http://jdbc:mysql://120.27.242.116:3306/eshop?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
